apiVersion: v1
kind: ConfigMap
metadata:
  name: example-service-conf
data:
  drink: {{ .Values.favouriteDrink }}
  food: {{ .Values.favouriteFood }}
  pastime: {{ default "nothing" .Values.favouritePastime }}
