apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-service
  name: example-service
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
      - name: example-service
        command: ['sleep', 'infinity']
        image: alpine
